package com.mbostic.employeeslist;

import android.content.Intent;
import android.database.Cursor;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import java.util.Locale;

import static com.mbostic.employeeslist.DBHelper.EMPLOYEES_COLUMN_BIRTH_DATE;
import static com.mbostic.employeeslist.DBHelper.EMPLOYEES_COLUMN_GENDER;
import static com.mbostic.employeeslist.DBHelper.EMPLOYEES_COLUMN_NAME;
import static com.mbostic.employeeslist.DBHelper.EMPLOYEES_COLUMN_SALARY;
import static com.mbostic.employeeslist.DBHelper.GENDER_MALE;

/**
 * Shows the selected employee's information.
 * The information is: Name, Id (autogenerated), Birthday date, Gender and Salary
 */
public class EmployeeProfileActivity extends AppCompatActivity {

    private String name;

    /**
     * Fetches the employee's information from the database and displays it
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_employee_profile);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        int employeeId = getIntent().getIntExtra("employeeId", 0);

        DBHelper dbHelper = new DBHelper(this);
        Cursor employeeData = dbHelper.getData(employeeId);
        employeeData.moveToFirst();
        name = employeeData.getString(employeeData.getColumnIndex(EMPLOYEES_COLUMN_NAME));
        int gender = employeeData.getInt(employeeData.getColumnIndex(EMPLOYEES_COLUMN_GENDER));
        String birthDate = employeeData.getString(employeeData.getColumnIndex(EMPLOYEES_COLUMN_BIRTH_DATE));
        float salary = employeeData.getFloat(employeeData.getColumnIndex(EMPLOYEES_COLUMN_SALARY));

        TextView idTextView = findViewById(R.id.id);
        idTextView.setText(String.valueOf(employeeId));

        TextView nameTextView = findViewById(R.id.name);
        nameTextView.setText(name);

        TextView genderTextView = findViewById(R.id.gender);
        genderTextView.setText(gender == GENDER_MALE ? getString(R.string.male) : getString(R.string.female));

        TextView birthDateTextView = findViewById(R.id.birthDate);
        birthDateTextView.setText(birthDate);

        TextView salaryTextView = findViewById(R.id.salary);
        salaryTextView.setText(String.format(Locale.US,"%.2f %s", salary, getString(R.string.currency)));
    }

    /**
     * Opens an activity for viewing the first 5 results from google.com when searching for the name of the employee
     * @param view
     */
    public void onClickSearchOnGoogle(View view) {
        Intent i = new Intent(this, PublicProfileActivity.class);
        i.putExtra("name", name);
        startActivity(i);
    }
}
